# name = "As hi sh"
# print(len(name))
# print(name[0:3])
# print(name.upper())
# print(name.lower())
# print(name)
# print(name.rstrip("!"))
# print(name.replace("s", "t"))
# print(name.split(" "))
# print(name.capitalize())
# print(name.center(12))
# print(len(name))
# print(len(name.center(1)))
name = "ashish"
print(name.count("sh"))
print(name.endswith('h'))
print(name.find('h'))